# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: adapter/v1/adapter.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'adapter/v1/adapter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61\x64\x61pter/v1/adapter.proto\x12\nadapter.v1\"`\n\x0e\x43ompileRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x10\n\x08trace_id\x18\x02 \x01(\t\x12\x13\n\x0bsection_ids\x18\x03 \x03(\t\x12\x13\n\x0bttl_seconds\x18\x04 \x01(\x05\"L\n\x0f\x43ompileResponse\x12\x12\n\nadapter_id\x18\x01 \x01(\t\x12\x11\n\tsignature\x18\x02 \x01(\t\x12\x12\n\nexpires_at\x18\x03 \x01(\x03\"6\n\rVerifyRequest\x12\x12\n\nadapter_id\x18\x01 \x01(\t\x12\x11\n\tsignature\x18\x02 \x01(\t\"O\n\x0eVerifyResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12.\n\rprobe_results\x18\x02 \x03(\x0b\x32\x17.adapter.v1.ProbeResult\"A\n\x0bProbeResult\x12\x12\n\nprobe_name\x18\x01 \x01(\t\x12\x0e\n\x06passed\x18\x02 \x01(\x08\x12\x0e\n\x06\x64\x65tail\x18\x03 \x01(\t\"#\n\rRevokeRequest\x12\x12\n\nadapter_id\x18\x01 \x01(\t\"!\n\x0eRevokeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xd6\x01\n\x0e\x41\x64\x61pterService\x12\x42\n\x07\x43ompile\x12\x1a.adapter.v1.CompileRequest\x1a\x1b.adapter.v1.CompileResponse\x12?\n\x06Verify\x12\x19.adapter.v1.VerifyRequest\x1a\x1a.adapter.v1.VerifyResponse\x12?\n\x06Revoke\x12\x19.adapter.v1.RevokeRequest\x1a\x1a.adapter.v1.RevokeResponseB@Z>github.com/b11902156/rag-gateway/adapter/internal/pb/adapterpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'adapter.v1.adapter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z>github.com/b11902156/rag-gateway/adapter/internal/pb/adapterpb'
  _globals['_COMPILEREQUEST']._serialized_start=40
  _globals['_COMPILEREQUEST']._serialized_end=136
  _globals['_COMPILERESPONSE']._serialized_start=138
  _globals['_COMPILERESPONSE']._serialized_end=214
  _globals['_VERIFYREQUEST']._serialized_start=216
  _globals['_VERIFYREQUEST']._serialized_end=270
  _globals['_VERIFYRESPONSE']._serialized_start=272
  _globals['_VERIFYRESPONSE']._serialized_end=351
  _globals['_PROBERESULT']._serialized_start=353
  _globals['_PROBERESULT']._serialized_end=418
  _globals['_REVOKEREQUEST']._serialized_start=420
  _globals['_REVOKEREQUEST']._serialized_end=455
  _globals['_REVOKERESPONSE']._serialized_start=457
  _globals['_REVOKERESPONSE']._serialized_end=490
  _globals['_ADAPTERSERVICE']._serialized_start=493
  _globals['_ADAPTERSERVICE']._serialized_end=707
# @@protoc_insertion_point(module_scope)
