# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from adapter.v1 import adapter_pb2 as adapter_dot_v1_dot_adapter__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in adapter/v1/adapter_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AdapterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Compile = channel.unary_unary(
                '/adapter.v1.AdapterService/Compile',
                request_serializer=adapter_dot_v1_dot_adapter__pb2.CompileRequest.SerializeToString,
                response_deserializer=adapter_dot_v1_dot_adapter__pb2.CompileResponse.FromString,
                _registered_method=True)
        self.Verify = channel.unary_unary(
                '/adapter.v1.AdapterService/Verify',
                request_serializer=adapter_dot_v1_dot_adapter__pb2.VerifyRequest.SerializeToString,
                response_deserializer=adapter_dot_v1_dot_adapter__pb2.VerifyResponse.FromString,
                _registered_method=True)
        self.Revoke = channel.unary_unary(
                '/adapter.v1.AdapterService/Revoke',
                request_serializer=adapter_dot_v1_dot_adapter__pb2.RevokeRequest.SerializeToString,
                response_deserializer=adapter_dot_v1_dot_adapter__pb2.RevokeResponse.FromString,
                _registered_method=True)


class AdapterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Compile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Verify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Revoke(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdapterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Compile': grpc.unary_unary_rpc_method_handler(
                    servicer.Compile,
                    request_deserializer=adapter_dot_v1_dot_adapter__pb2.CompileRequest.FromString,
                    response_serializer=adapter_dot_v1_dot_adapter__pb2.CompileResponse.SerializeToString,
            ),
            'Verify': grpc.unary_unary_rpc_method_handler(
                    servicer.Verify,
                    request_deserializer=adapter_dot_v1_dot_adapter__pb2.VerifyRequest.FromString,
                    response_serializer=adapter_dot_v1_dot_adapter__pb2.VerifyResponse.SerializeToString,
            ),
            'Revoke': grpc.unary_unary_rpc_method_handler(
                    servicer.Revoke,
                    request_deserializer=adapter_dot_v1_dot_adapter__pb2.RevokeRequest.FromString,
                    response_serializer=adapter_dot_v1_dot_adapter__pb2.RevokeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'adapter.v1.AdapterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('adapter.v1.AdapterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdapterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Compile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adapter.v1.AdapterService/Compile',
            adapter_dot_v1_dot_adapter__pb2.CompileRequest.SerializeToString,
            adapter_dot_v1_dot_adapter__pb2.CompileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Verify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adapter.v1.AdapterService/Verify',
            adapter_dot_v1_dot_adapter__pb2.VerifyRequest.SerializeToString,
            adapter_dot_v1_dot_adapter__pb2.VerifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Revoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adapter.v1.AdapterService/Revoke',
            adapter_dot_v1_dot_adapter__pb2.RevokeRequest.SerializeToString,
            adapter_dot_v1_dot_adapter__pb2.RevokeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
