# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: retrieval/v1/retrieval.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'retrieval/v1/retrieval.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cretrieval/v1/retrieval.proto\x12\x0cretrieval.v1\"\xc7\x01\n\x0fRetrieveRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x10\n\x08trace_id\x18\x02 \x01(\t\x12\r\n\x05top_k\x18\x03 \x01(\x05\x12L\n\x10metadata_filters\x18\x04 \x03(\x0b\x32\x32.retrieval.v1.RetrieveRequest.MetadataFiltersEntry\x1a\x36\n\x14MetadataFiltersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"D\n\x10RetrieveResponse\x12\x30\n\x08sections\x18\x01 \x03(\x0b\x32\x1e.retrieval.v1.RetrievedSection\"\xe0\x01\n\x10RetrievedSection\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\x12\x12\n\nsection_id\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\r\n\x05score\x18\x04 \x01(\x02\x12\x12\n\ntrust_tier\x18\x05 \x01(\t\x12>\n\x08metadata\x18\x06 \x03(\x0b\x32,.retrieval.v1.RetrievedSection.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xa1\x01\n\x0cIndexRequest\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12:\n\x08metadata\x18\x03 \x03(\x0b\x32(.retrieval.v1.IndexRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"1\n\rIndexResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x9f\x01\n\x10RetrievalService\x12I\n\x08Retrieve\x12\x1d.retrieval.v1.RetrieveRequest\x1a\x1e.retrieval.v1.RetrieveResponse\x12@\n\x05Index\x12\x1a.retrieval.v1.IndexRequest\x1a\x1b.retrieval.v1.IndexResponseBDZBgithub.com/b11902156/rag-gateway/retrieval/internal/pb/retrievalpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'retrieval.v1.retrieval_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZBgithub.com/b11902156/rag-gateway/retrieval/internal/pb/retrievalpb'
  _globals['_RETRIEVEREQUEST_METADATAFILTERSENTRY']._loaded_options = None
  _globals['_RETRIEVEREQUEST_METADATAFILTERSENTRY']._serialized_options = b'8\001'
  _globals['_RETRIEVEDSECTION_METADATAENTRY']._loaded_options = None
  _globals['_RETRIEVEDSECTION_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_INDEXREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_INDEXREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_RETRIEVEREQUEST']._serialized_start=47
  _globals['_RETRIEVEREQUEST']._serialized_end=246
  _globals['_RETRIEVEREQUEST_METADATAFILTERSENTRY']._serialized_start=192
  _globals['_RETRIEVEREQUEST_METADATAFILTERSENTRY']._serialized_end=246
  _globals['_RETRIEVERESPONSE']._serialized_start=248
  _globals['_RETRIEVERESPONSE']._serialized_end=316
  _globals['_RETRIEVEDSECTION']._serialized_start=319
  _globals['_RETRIEVEDSECTION']._serialized_end=543
  _globals['_RETRIEVEDSECTION_METADATAENTRY']._serialized_start=496
  _globals['_RETRIEVEDSECTION_METADATAENTRY']._serialized_end=543
  _globals['_INDEXREQUEST']._serialized_start=546
  _globals['_INDEXREQUEST']._serialized_end=707
  _globals['_INDEXREQUEST_METADATAENTRY']._serialized_start=496
  _globals['_INDEXREQUEST_METADATAENTRY']._serialized_end=543
  _globals['_INDEXRESPONSE']._serialized_start=709
  _globals['_INDEXRESPONSE']._serialized_end=758
  _globals['_RETRIEVALSERVICE']._serialized_start=761
  _globals['_RETRIEVALSERVICE']._serialized_end=920
# @@protoc_insertion_point(module_scope)
