// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: adapter/v1/adapter.proto

package adapterpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SectionIds    []string               `protobuf:"bytes,3,rep,name=section_ids,json=sectionIds,proto3" json:"section_ids,omitempty"`
	TtlSeconds    int32                  `protobuf:"varint,4,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompileRequest) Reset() {
	*x = CompileRequest{}
	mi := &file_adapter_v1_adapter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileRequest) ProtoMessage() {}

func (x *CompileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adapter_v1_adapter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileRequest.ProtoReflect.Descriptor instead.
func (*CompileRequest) Descriptor() ([]byte, []int) {
	return file_adapter_v1_adapter_proto_rawDescGZIP(), []int{0}
}

func (x *CompileRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CompileRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *CompileRequest) GetSectionIds() []string {
	if x != nil {
		return x.SectionIds
	}
	return nil
}

func (x *CompileRequest) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type CompileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdapterId     string                 `protobuf:"bytes,1,opt,name=adapter_id,json=adapterId,proto3" json:"adapter_id,omitempty"`
	Signature     string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompileResponse) Reset() {
	*x = CompileResponse{}
	mi := &file_adapter_v1_adapter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileResponse) ProtoMessage() {}

func (x *CompileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adapter_v1_adapter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileResponse.ProtoReflect.Descriptor instead.
func (*CompileResponse) Descriptor() ([]byte, []int) {
	return file_adapter_v1_adapter_proto_rawDescGZIP(), []int{1}
}

func (x *CompileResponse) GetAdapterId() string {
	if x != nil {
		return x.AdapterId
	}
	return ""
}

func (x *CompileResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *CompileResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type VerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdapterId     string                 `protobuf:"bytes,1,opt,name=adapter_id,json=adapterId,proto3" json:"adapter_id,omitempty"`
	Signature     string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_adapter_v1_adapter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adapter_v1_adapter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_adapter_v1_adapter_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyRequest) GetAdapterId() string {
	if x != nil {
		return x.AdapterId
	}
	return ""
}

func (x *VerifyRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type VerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	ProbeResults  []*ProbeResult         `protobuf:"bytes,2,rep,name=probe_results,json=probeResults,proto3" json:"probe_results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_adapter_v1_adapter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adapter_v1_adapter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_adapter_v1_adapter_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyResponse) GetProbeResults() []*ProbeResult {
	if x != nil {
		return x.ProbeResults
	}
	return nil
}

type ProbeResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProbeName     string                 `protobuf:"bytes,1,opt,name=probe_name,json=probeName,proto3" json:"probe_name,omitempty"`
	Passed        bool                   `protobuf:"varint,2,opt,name=passed,proto3" json:"passed,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeResult) Reset() {
	*x = ProbeResult{}
	mi := &file_adapter_v1_adapter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeResult) ProtoMessage() {}

func (x *ProbeResult) ProtoReflect() protoreflect.Message {
	mi := &file_adapter_v1_adapter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeResult.ProtoReflect.Descriptor instead.
func (*ProbeResult) Descriptor() ([]byte, []int) {
	return file_adapter_v1_adapter_proto_rawDescGZIP(), []int{4}
}

func (x *ProbeResult) GetProbeName() string {
	if x != nil {
		return x.ProbeName
	}
	return ""
}

func (x *ProbeResult) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *ProbeResult) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type RevokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdapterId     string                 `protobuf:"bytes,1,opt,name=adapter_id,json=adapterId,proto3" json:"adapter_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRequest) Reset() {
	*x = RevokeRequest{}
	mi := &file_adapter_v1_adapter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRequest) ProtoMessage() {}

func (x *RevokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adapter_v1_adapter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRequest.ProtoReflect.Descriptor instead.
func (*RevokeRequest) Descriptor() ([]byte, []int) {
	return file_adapter_v1_adapter_proto_rawDescGZIP(), []int{5}
}

func (x *RevokeRequest) GetAdapterId() string {
	if x != nil {
		return x.AdapterId
	}
	return ""
}

type RevokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeResponse) Reset() {
	*x = RevokeResponse{}
	mi := &file_adapter_v1_adapter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeResponse) ProtoMessage() {}

func (x *RevokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adapter_v1_adapter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeResponse.ProtoReflect.Descriptor instead.
func (*RevokeResponse) Descriptor() ([]byte, []int) {
	return file_adapter_v1_adapter_proto_rawDescGZIP(), []int{6}
}

func (x *RevokeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_adapter_v1_adapter_proto protoreflect.FileDescriptor

const file_adapter_v1_adapter_proto_rawDesc = "" +
	"\n" +
	"\x18adapter/v1/adapter.proto\x12\n" +
	"adapter.v1\"\x8c\x01\n" +
	"\x0eCompileRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12\x1f\n" +
	"\vsection_ids\x18\x03 \x03(\tR\n" +
	"sectionIds\x12\x1f\n" +
	"\vttl_seconds\x18\x04 \x01(\x05R\n" +
	"ttlSeconds\"m\n" +
	"\x0fCompileResponse\x12\x1d\n" +
	"\n" +
	"adapter_id\x18\x01 \x01(\tR\tadapterId\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\"L\n" +
	"\rVerifyRequest\x12\x1d\n" +
	"\n" +
	"adapter_id\x18\x01 \x01(\tR\tadapterId\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\"d\n" +
	"\x0eVerifyResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12<\n" +
	"\rprobe_results\x18\x02 \x03(\v2\x17.adapter.v1.ProbeResultR\fprobeResults\"\\\n" +
	"\vProbeResult\x12\x1d\n" +
	"\n" +
	"probe_name\x18\x01 \x01(\tR\tprobeName\x12\x16\n" +
	"\x06passed\x18\x02 \x01(\bR\x06passed\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\".\n" +
	"\rRevokeRequest\x12\x1d\n" +
	"\n" +
	"adapter_id\x18\x01 \x01(\tR\tadapterId\"*\n" +
	"\x0eRevokeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xd6\x01\n" +
	"\x0eAdapterService\x12B\n" +
	"\aCompile\x12\x1a.adapter.v1.CompileRequest\x1a\x1b.adapter.v1.CompileResponse\x12?\n" +
	"\x06Verify\x12\x19.adapter.v1.VerifyRequest\x1a\x1a.adapter.v1.VerifyResponse\x12?\n" +
	"\x06Revoke\x12\x19.adapter.v1.RevokeRequest\x1a\x1a.adapter.v1.RevokeResponseB@Z>github.com/b11902156/rag-gateway/adapter/internal/pb/adapterpbb\x06proto3"

var (
	file_adapter_v1_adapter_proto_rawDescOnce sync.Once
	file_adapter_v1_adapter_proto_rawDescData []byte
)

func file_adapter_v1_adapter_proto_rawDescGZIP() []byte {
	file_adapter_v1_adapter_proto_rawDescOnce.Do(func() {
		file_adapter_v1_adapter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_adapter_v1_adapter_proto_rawDesc), len(file_adapter_v1_adapter_proto_rawDesc)))
	})
	return file_adapter_v1_adapter_proto_rawDescData
}

var file_adapter_v1_adapter_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_adapter_v1_adapter_proto_goTypes = []any{
	(*CompileRequest)(nil),  // 0: adapter.v1.CompileRequest
	(*CompileResponse)(nil), // 1: adapter.v1.CompileResponse
	(*VerifyRequest)(nil),   // 2: adapter.v1.VerifyRequest
	(*VerifyResponse)(nil),  // 3: adapter.v1.VerifyResponse
	(*ProbeResult)(nil),     // 4: adapter.v1.ProbeResult
	(*RevokeRequest)(nil),   // 5: adapter.v1.RevokeRequest
	(*RevokeResponse)(nil),  // 6: adapter.v1.RevokeResponse
}
var file_adapter_v1_adapter_proto_depIdxs = []int32{
	4, // 0: adapter.v1.VerifyResponse.probe_results:type_name -> adapter.v1.ProbeResult
	0, // 1: adapter.v1.AdapterService.Compile:input_type -> adapter.v1.CompileRequest
	2, // 2: adapter.v1.AdapterService.Verify:input_type -> adapter.v1.VerifyRequest
	5, // 3: adapter.v1.AdapterService.Revoke:input_type -> adapter.v1.RevokeRequest
	1, // 4: adapter.v1.AdapterService.Compile:output_type -> adapter.v1.CompileResponse
	3, // 5: adapter.v1.AdapterService.Verify:output_type -> adapter.v1.VerifyResponse
	6, // 6: adapter.v1.AdapterService.Revoke:output_type -> adapter.v1.RevokeResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_adapter_v1_adapter_proto_init() }
func file_adapter_v1_adapter_proto_init() {
	if File_adapter_v1_adapter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_adapter_v1_adapter_proto_rawDesc), len(file_adapter_v1_adapter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_adapter_v1_adapter_proto_goTypes,
		DependencyIndexes: file_adapter_v1_adapter_proto_depIdxs,
		MessageInfos:      file_adapter_v1_adapter_proto_msgTypes,
	}.Build()
	File_adapter_v1_adapter_proto = out.File
	file_adapter_v1_adapter_proto_goTypes = nil
	file_adapter_v1_adapter_proto_depIdxs = nil
}
