// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: retrieval/v1/retrieval.proto

package retrievalpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RetrieveRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Query           string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	TraceId         string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	TopK            int32                  `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	MetadataFilters map[string]string      `protobuf:"bytes,4,rep,name=metadata_filters,json=metadataFilters,proto3" json:"metadata_filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RetrieveRequest) Reset() {
	*x = RetrieveRequest{}
	mi := &file_retrieval_v1_retrieval_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveRequest) ProtoMessage() {}

func (x *RetrieveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_v1_retrieval_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveRequest.ProtoReflect.Descriptor instead.
func (*RetrieveRequest) Descriptor() ([]byte, []int) {
	return file_retrieval_v1_retrieval_proto_rawDescGZIP(), []int{0}
}

func (x *RetrieveRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RetrieveRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *RetrieveRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *RetrieveRequest) GetMetadataFilters() map[string]string {
	if x != nil {
		return x.MetadataFilters
	}
	return nil
}

type RetrieveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sections      []*RetrievedSection    `protobuf:"bytes,1,rep,name=sections,proto3" json:"sections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveResponse) Reset() {
	*x = RetrieveResponse{}
	mi := &file_retrieval_v1_retrieval_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveResponse) ProtoMessage() {}

func (x *RetrieveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_v1_retrieval_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveResponse.ProtoReflect.Descriptor instead.
func (*RetrieveResponse) Descriptor() ([]byte, []int) {
	return file_retrieval_v1_retrieval_proto_rawDescGZIP(), []int{1}
}

func (x *RetrieveResponse) GetSections() []*RetrievedSection {
	if x != nil {
		return x.Sections
	}
	return nil
}

type RetrievedSection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	SectionId     string                 `protobuf:"bytes,2,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Score         float32                `protobuf:"fixed32,4,opt,name=score,proto3" json:"score,omitempty"`
	TrustTier     string                 `protobuf:"bytes,5,opt,name=trust_tier,json=trustTier,proto3" json:"trust_tier,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrievedSection) Reset() {
	*x = RetrievedSection{}
	mi := &file_retrieval_v1_retrieval_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrievedSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrievedSection) ProtoMessage() {}

func (x *RetrievedSection) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_v1_retrieval_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrievedSection.ProtoReflect.Descriptor instead.
func (*RetrievedSection) Descriptor() ([]byte, []int) {
	return file_retrieval_v1_retrieval_proto_rawDescGZIP(), []int{2}
}

func (x *RetrievedSection) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *RetrievedSection) GetSectionId() string {
	if x != nil {
		return x.SectionId
	}
	return ""
}

func (x *RetrievedSection) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RetrievedSection) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RetrievedSection) GetTrustTier() string {
	if x != nil {
		return x.TrustTier
	}
	return ""
}

func (x *RetrievedSection) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type IndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexRequest) Reset() {
	*x = IndexRequest{}
	mi := &file_retrieval_v1_retrieval_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexRequest) ProtoMessage() {}

func (x *IndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_v1_retrieval_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexRequest.ProtoReflect.Descriptor instead.
func (*IndexRequest) Descriptor() ([]byte, []int) {
	return file_retrieval_v1_retrieval_proto_rawDescGZIP(), []int{3}
}

func (x *IndexRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *IndexRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *IndexRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type IndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexResponse) Reset() {
	*x = IndexResponse{}
	mi := &file_retrieval_v1_retrieval_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexResponse) ProtoMessage() {}

func (x *IndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_v1_retrieval_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexResponse.ProtoReflect.Descriptor instead.
func (*IndexResponse) Descriptor() ([]byte, []int) {
	return file_retrieval_v1_retrieval_proto_rawDescGZIP(), []int{4}
}

func (x *IndexResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IndexResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_retrieval_v1_retrieval_proto protoreflect.FileDescriptor

const file_retrieval_v1_retrieval_proto_rawDesc = "" +
	"\n" +
	"\x1cretrieval/v1/retrieval.proto\x12\fretrieval.v1\"\xfa\x01\n" +
	"\x0fRetrieveRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\x05R\x04topK\x12]\n" +
	"\x10metadata_filters\x18\x04 \x03(\v22.retrieval.v1.RetrieveRequest.MetadataFiltersEntryR\x0fmetadataFilters\x1aB\n" +
	"\x14MetadataFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"N\n" +
	"\x10RetrieveResponse\x12:\n" +
	"\bsections\x18\x01 \x03(\v2\x1e.retrieval.v1.RetrievedSectionR\bsections\"\xa8\x02\n" +
	"\x10RetrievedSection\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x1d\n" +
	"\n" +
	"section_id\x18\x02 \x01(\tR\tsectionId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x02R\x05score\x12\x1d\n" +
	"\n" +
	"trust_tier\x18\x05 \x01(\tR\ttrustTier\x12H\n" +
	"\bmetadata\x18\x06 \x03(\v2,.retrieval.v1.RetrievedSection.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcc\x01\n" +
	"\fIndexRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12D\n" +
	"\bmetadata\x18\x03 \x03(\v2(.retrieval.v1.IndexRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"C\n" +
	"\rIndexResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x9f\x01\n" +
	"\x10RetrievalService\x12I\n" +
	"\bRetrieve\x12\x1d.retrieval.v1.RetrieveRequest\x1a\x1e.retrieval.v1.RetrieveResponse\x12@\n" +
	"\x05Index\x12\x1a.retrieval.v1.IndexRequest\x1a\x1b.retrieval.v1.IndexResponseBDZBgithub.com/b11902156/rag-gateway/retrieval/internal/pb/retrievalpbb\x06proto3"

var (
	file_retrieval_v1_retrieval_proto_rawDescOnce sync.Once
	file_retrieval_v1_retrieval_proto_rawDescData []byte
)

func file_retrieval_v1_retrieval_proto_rawDescGZIP() []byte {
	file_retrieval_v1_retrieval_proto_rawDescOnce.Do(func() {
		file_retrieval_v1_retrieval_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_retrieval_v1_retrieval_proto_rawDesc), len(file_retrieval_v1_retrieval_proto_rawDesc)))
	})
	return file_retrieval_v1_retrieval_proto_rawDescData
}

var file_retrieval_v1_retrieval_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_retrieval_v1_retrieval_proto_goTypes = []any{
	(*RetrieveRequest)(nil),  // 0: retrieval.v1.RetrieveRequest
	(*RetrieveResponse)(nil), // 1: retrieval.v1.RetrieveResponse
	(*RetrievedSection)(nil), // 2: retrieval.v1.RetrievedSection
	(*IndexRequest)(nil),     // 3: retrieval.v1.IndexRequest
	(*IndexResponse)(nil),    // 4: retrieval.v1.IndexResponse
	nil,                      // 5: retrieval.v1.RetrieveRequest.MetadataFiltersEntry
	nil,                      // 6: retrieval.v1.RetrievedSection.MetadataEntry
	nil,                      // 7: retrieval.v1.IndexRequest.MetadataEntry
}
var file_retrieval_v1_retrieval_proto_depIdxs = []int32{
	5, // 0: retrieval.v1.RetrieveRequest.metadata_filters:type_name -> retrieval.v1.RetrieveRequest.MetadataFiltersEntry
	2, // 1: retrieval.v1.RetrieveResponse.sections:type_name -> retrieval.v1.RetrievedSection
	6, // 2: retrieval.v1.RetrievedSection.metadata:type_name -> retrieval.v1.RetrievedSection.MetadataEntry
	7, // 3: retrieval.v1.IndexRequest.metadata:type_name -> retrieval.v1.IndexRequest.MetadataEntry
	0, // 4: retrieval.v1.RetrievalService.Retrieve:input_type -> retrieval.v1.RetrieveRequest
	3, // 5: retrieval.v1.RetrievalService.Index:input_type -> retrieval.v1.IndexRequest
	1, // 6: retrieval.v1.RetrievalService.Retrieve:output_type -> retrieval.v1.RetrieveResponse
	4, // 7: retrieval.v1.RetrievalService.Index:output_type -> retrieval.v1.IndexResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_retrieval_v1_retrieval_proto_init() }
func file_retrieval_v1_retrieval_proto_init() {
	if File_retrieval_v1_retrieval_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_retrieval_v1_retrieval_proto_rawDesc), len(file_retrieval_v1_retrieval_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_retrieval_v1_retrieval_proto_goTypes,
		DependencyIndexes: file_retrieval_v1_retrieval_proto_depIdxs,
		MessageInfos:      file_retrieval_v1_retrieval_proto_msgTypes,
	}.Build()
	File_retrieval_v1_retrieval_proto = out.File
	file_retrieval_v1_retrieval_proto_goTypes = nil
	file_retrieval_v1_retrieval_proto_depIdxs = nil
}
