// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: retrieval/v1/retrieval.proto

package retrievalpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RetrievalService_Retrieve_FullMethodName = "/retrieval.v1.RetrievalService/Retrieve"
	RetrievalService_Index_FullMethodName    = "/retrieval.v1.RetrievalService/Index"
)

// RetrievalServiceClient is the client API for RetrievalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RetrievalServiceClient interface {
	Retrieve(ctx context.Context, in *RetrieveRequest, opts ...grpc.CallOption) (*RetrieveResponse, error)
	Index(ctx context.Context, in *IndexRequest, opts ...grpc.CallOption) (*IndexResponse, error)
}

type retrievalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRetrievalServiceClient(cc grpc.ClientConnInterface) RetrievalServiceClient {
	return &retrievalServiceClient{cc}
}

func (c *retrievalServiceClient) Retrieve(ctx context.Context, in *RetrieveRequest, opts ...grpc.CallOption) (*RetrieveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrieveResponse)
	err := c.cc.Invoke(ctx, RetrievalService_Retrieve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *retrievalServiceClient) Index(ctx context.Context, in *IndexRequest, opts ...grpc.CallOption) (*IndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IndexResponse)
	err := c.cc.Invoke(ctx, RetrievalService_Index_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RetrievalServiceServer is the server API for RetrievalService service.
// All implementations must embed UnimplementedRetrievalServiceServer
// for forward compatibility.
type RetrievalServiceServer interface {
	Retrieve(context.Context, *RetrieveRequest) (*RetrieveResponse, error)
	Index(context.Context, *IndexRequest) (*IndexResponse, error)
	mustEmbedUnimplementedRetrievalServiceServer()
}

// UnimplementedRetrievalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRetrievalServiceServer struct{}

func (UnimplementedRetrievalServiceServer) Retrieve(context.Context, *RetrieveRequest) (*RetrieveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Retrieve not implemented")
}
func (UnimplementedRetrievalServiceServer) Index(context.Context, *IndexRequest) (*IndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Index not implemented")
}
func (UnimplementedRetrievalServiceServer) mustEmbedUnimplementedRetrievalServiceServer() {}
func (UnimplementedRetrievalServiceServer) testEmbeddedByValue()                          {}

// UnsafeRetrievalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RetrievalServiceServer will
// result in compilation errors.
type UnsafeRetrievalServiceServer interface {
	mustEmbedUnimplementedRetrievalServiceServer()
}

func RegisterRetrievalServiceServer(s grpc.ServiceRegistrar, srv RetrievalServiceServer) {
	// If the following call panics, it indicates UnimplementedRetrievalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RetrievalService_ServiceDesc, srv)
}

func _RetrievalService_Retrieve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RetrievalServiceServer).Retrieve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RetrievalService_Retrieve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RetrievalServiceServer).Retrieve(ctx, req.(*RetrieveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RetrievalService_Index_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RetrievalServiceServer).Index(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RetrievalService_Index_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RetrievalServiceServer).Index(ctx, req.(*IndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RetrievalService_ServiceDesc is the grpc.ServiceDesc for RetrievalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RetrievalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "retrieval.v1.RetrievalService",
	HandlerType: (*RetrievalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Retrieve",
			Handler:    _RetrievalService_Retrieve_Handler,
		},
		{
			MethodName: "Index",
			Handler:    _RetrievalService_Index_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "retrieval/v1/retrieval.proto",
}
